### ISSUE TITLE
Missing tooltips?

### ISSUE THREAD

**Issue by allanwrosenow** [sbaril/Photoshop-Animation#1]
I followed install instructions and have a fully functional toolbar, except there are no tooltips on hover. Is this as intended, or are there supposed to be tooltips? It's difficult to remember what the buttons all do.

- 10.12.6 Sierra MacOS
- Adobe Photoshop CC 2018

**Comment by sbaril** [comment]
Hi Allan,
Sorry but there is no tooltips but, if it can help, you'll find here a reminder:
[AnimDessin2_User_Guide_01](https://www.dropbox.com/s/oiogc2sfsgjkg3g/AnimDessin2_User_Guide_01.pdf?dl=1)
Hope that will help!

**Comment by schroef** [comment]
I know this is closed, but why don't you add a tooltip? This will help beginners a lot, since currently you need to either memorize each function or keep that PDF aside. Im just giving UX feedback here. Its a great addon, but it could use some small touch-ups i think

**Comment by schroef** [comment]
Im working on something here. I did some digging and seems for Window Tooltips work out of the box. However for OSX they don't. Im doing a test with some code i found and seems to work.

![Tooltips-css-bootsrap](https://user-images.githubusercontent.com/6923008/77472784-d0bc5600-6dea-11ea-8b53-ef727991674f.gif)
