### ISSUE TITLE
Vimeo videos inaccessible for public viewing

### ISSUE THREAD

**Issue by nyxmon** [sbaril/Photoshop-Animation#11]
Hi Stephane,

I'm an amateur animator with decent amount of knowledge in Photoshop and was starting to get into the paperless traditional workflow on Photoshop, through I discovered your amazing plugins - **AnimDessin2** and **AnimCouleur2**

While I've got absoutely nothing but massive respect for what you've done to make the tools of the trade more widely accessible to the public, I believe the lessons required to learn the same is essential.

I have seen your Vimeo videos in Google preview links and listed here too, but whenever I try to open any video it always opens the following [listed below]. Can you look into the issue or provide other links where your videos are available?

![1](https://user-images.githubusercontent.com/66380934/84286093-df99e580-ab5b-11ea-9adc-a1abceb00815.png)
![2](https://user-images.githubusercontent.com/66380934/84286096-e163a900-ab5b-11ea-9245-ee398c77cd86.png)
![3](https://user-images.githubusercontent.com/66380934/84286098-e1fc3f80-ab5b-11ea-9eb3-5d7af12e570b.png)

Thanks a lot, regardless - and have a nice day!

**Comment by sbaril** [comment]
Yes until June 24th and I will migrate all the content on my YouTube Channel.
Thanks again for the heads up 👍
