### ISSUE TITLE
Mac Disk permission problem with AnimDessin2

### ISSUE THREAD

**Issue by GimmyBear** [sbaril/Photoshop-Animation#23]
hi, I'm a mac user and phtotshop 2021

I have downloaded and installed Extension Manager successfully ; however i just can't install AnimDessin2 into Extention Manager.

It shows that i have disk Utility Problem, so i found n repaired my disk and allowed full access for both Extension Manager and Photoshop, and nothing helped.
<img width="247" alt="截圖 2022-07-20 下午8 27 51" src="https://user-images.githubusercontent.com/90551176/179983443-01c4a34a-f0c6-4cf0-8045-b13f1a1acfcc.png">

could anyone tell me what should i do, tks

**Comment by schroef** [comment]
Thats is kinda weird, this extension does nothing to the disk in those terms. You could try the manual installation, you need to follow the steps as shown on the main page. You need to enter the commands to allow debugging, codes need to be entered in Terminal or CMD line

**Comment by GimmyBear** [comment]
ＯＭＧ ！ it works, finally ! 
Thank you for your elaborating guide and efforts on all this.

**Comment by schroef** [comment]
Ps if you want a version with more functionality look at my GitHub. I have version which has many new functions. You do need to install this one manually

Look at issue #8 near the bottom, you'll find a link to my repository and some instructions in that post on how to get it activated

Did you use the manual method now?
