### ISSUE TITLE
A very strange issue and I really need your help. FrameMinusOne and FramePlusOne not working. All other commands are good.

### ISSUE THREAD

**Issue by mikeouwen** [sbaril/Photoshop-Animation#7]
![image](https://user-images.githubusercontent.com/6271251/71705003-3b777a00-2e18-11ea-8cfd-3382cfcfd491.png)
Every time I use FrameMinusOne or FramePlusOne Photoshop gives me this error. All other commands work as normal. I tried to load these two specific scripts using Script->Browse, but Photoshop gives me Javascript code was missing error like this:
![image](https://user-images.githubusercontent.com/6271251/71705045-83969c80-2e18-11ea-8a91-7826ce888546.png)

All commands worked when I first used it but somehow later the F+1 and F-1 commands corrupted.

Please help me.

**Comment by schroef** [comment]
Does the panel itself work properly, i mean do the buttons work?

PS I've upgrade the panel, you can find mine here. You can now do all actions on multiple layers. Most tools buttons have now 2-3 options, so tons of new features. I just finished cleaning today and looking for test cases.

Ive added help guide for all the new functions, see right-click menu or the panel menu. Also settings are now saved
you can find it here https://github.com/schroef/AnimDessin2

**Comment by sbaril** [comment]
If I well remember, I already answered to mikeouwen in an other channel and it works fine now.
Actually mikeouwen found that this two JSX, for some reason, were not encoded in UTF-8 and so in some localization it failed.
I fixed the Scripts available on GitHub, so he could replace is scripts but not released yet a new AnimDessin2 ZXP.

**Comment by schroef** [comment]
Thats weird, because scripts arent not encode as UTF-8 i believe. Thats only for text files and other text related files. Script files show their own language in the encode i believe, as far as i have knowledge of that.

**Comment by mikeouwen** [comment]
> If I well remember, I already answered to mikeouwen in an other channel and it works fine now.
> Actually mikeouwen found that this two JSX, for some reason, were not encoded in UTF-8 and so in some localization it failed.
> I fixed the Scripts available on GitHub, so he could replace is scripts but not released yet a new AnimDessin2 ZXP.

Yes. It's me. I forgot to close this question. Thank you. I'll close it now.
